/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package vistas;

import javax.swing.JOptionPane;
import modelo.beans.Usuario;
import modelo.logic.UsuarioLogic;

/**
 *
 * @author Oyunde
 */
public class FrmRegistrarUsuario extends javax.swing.JDialog {

    /**
     * Creates new form FrmRegistrarUsuario
     */
    public FrmRegistrarUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //para centrar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_registroUsuarios = new javax.swing.JLabel();
        lbl_usuarios = new javax.swing.JLabel();
        lbl_contrasenia = new javax.swing.JLabel();
        lbl_nombres = new javax.swing.JLabel();
        lbl_apellidos = new javax.swing.JLabel();
        lbl_correo = new javax.swing.JLabel();
        txt_contrasenia = new javax.swing.JPasswordField();
        txt_usuario = new javax.swing.JTextField();
        txt_correo = new javax.swing.JTextField();
        txt_apellidos = new javax.swing.JTextField();
        txt_nombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txt_repetirContrasenia = new javax.swing.JPasswordField();
        btn_registrar = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_registroUsuarios.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_registroUsuarios.setText("Registro de usuario");
        getContentPane().add(lbl_registroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 53, -1, -1));

        lbl_usuarios.setText("Usuario");
        getContentPane().add(lbl_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 234, -1, -1));

        lbl_contrasenia.setText("Contraseña");
        getContentPane().add(lbl_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(107, 274, -1, -1));

        lbl_nombres.setText("Nombres");
        getContentPane().add(lbl_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 114, -1, -1));

        lbl_apellidos.setText("Apelllidos");
        getContentPane().add(lbl_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 154, -1, -1));

        lbl_correo.setText("Correo");
        getContentPane().add(lbl_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 194, -1, -1));

        txt_contrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_contraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_contrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 271, 243, -1));

        txt_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usuarioActionPerformed(evt);
            }
        });
        getContentPane().add(txt_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 231, 243, -1));
        getContentPane().add(txt_correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 191, 243, -1));
        getContentPane().add(txt_apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 151, 243, -1));
        getContentPane().add(txt_nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 111, 243, -1));

        jLabel1.setText("Repetir contraseña");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 314, -1, -1));
        getContentPane().add(txt_repetirContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 311, 243, -1));

        btn_registrar.setText("Registrar");
        btn_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_registrarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_registrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 376, -1, -1));

        btn_modificar.setText("Modificar");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(249, 376, -1, -1));

        btn_eliminar.setText("Eliminar");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 376, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/registro_usuario.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_contraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_contraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_contraseniaActionPerformed

    private void txt_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usuarioActionPerformed

    private void btn_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_registrarActionPerformed
        // TODO add your handling code here:
        if(!txt_nombres.getText().isEmpty() &&       
                !txt_apellidos.getText().isEmpty()&& 
                !txt_correo.getText().isEmpty() && 
                !txt_usuario.getText().isEmpty() &&
                !txt_contrasenia.getText().isEmpty() && 
                 txt_repetirContrasenia.getText().equals(txt_contrasenia.getText())){
            
            Usuario usuario = new Usuario(txt_usuario.getText(), txt_contrasenia.getText(),
                    txt_nombres.getText(), txt_apellidos.getText(), txt_correo.getText());
            
            
            System.out.println(usuario);
            
            if(UsuarioLogic.insertar(usuario)) {
                JOptionPane.showMessageDialog(this, "Usuario registrado exitosamente");
                
                System.out.println(usuario.getUsuario());
                System.out.println(usuario.getContrasenia());
                
                UsuarioLogic.listar();
            }else {
                JOptionPane.showMessageDialog(this, "Usuario existente");
            }
        }
    }//GEN-LAST:event_btn_registrarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        if(!txt_nombres.getText().isEmpty() &&       
                !txt_apellidos.getText().isEmpty()&& 
                !txt_correo.getText().isEmpty() && 
                !txt_usuario.getText().isEmpty() &&
                !txt_contrasenia.getText().isEmpty() && 
                txt_repetirContrasenia.getText().equals(txt_contrasenia.getText())){
            
            Usuario usuario = new Usuario(txt_usuario.getText(),
                    txt_contrasenia.getText() , txt_nombres.getText(), txt_apellidos.getText(), txt_correo.getText());
            if(UsuarioLogic.modificar(usuario)) {
                JOptionPane.showMessageDialog(this, "Usuario modificado exitosamente");
            }else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }
           
        }else{
        }
        
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        // TODO add your handling code here:
        if(txt_usuario.getText().isEmpty()){
            if(UsuarioLogic.eliminar(txt_usuario.getText())) {
                JOptionPane.showMessageDialog(this, "Usuario eliminado exitosamente");
            }else {
                JOptionPane.showMessageDialog(this, "Usuario no encontrado");
            }
           
        }else{
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmRegistrarUsuario dialog = new FrmRegistrarUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_registrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbl_apellidos;
    private javax.swing.JLabel lbl_contrasenia;
    private javax.swing.JLabel lbl_correo;
    private javax.swing.JLabel lbl_nombres;
    private javax.swing.JLabel lbl_registroUsuarios;
    private javax.swing.JLabel lbl_usuarios;
    private javax.swing.JTextField txt_apellidos;
    private javax.swing.JPasswordField txt_contrasenia;
    private javax.swing.JTextField txt_correo;
    private javax.swing.JTextField txt_nombres;
    private javax.swing.JPasswordField txt_repetirContrasenia;
    private javax.swing.JTextField txt_usuario;
    // End of variables declaration//GEN-END:variables
}
